### ISSUE TITLE
submit 오류

### ISSUE THREAD

**Issue by gearmlai** [ai-starthon/AI_Starthon2019#144]
안녕하세요 submit 과정에서 에러가 발생했는데 원인파악이 안됩니다.

환경: 윈도우 10
명령어: nsml --test submit team_153/8_iret_food/9 16

Session team_153/8_iret_food/12 is started
.Inference the test set. The inference should be completed within 3600 seconds.
.Traceback (most recent call last):
  File "/app/nsml/data_loader.py", line 20, in feed_infer
    top1_reference_ids = infer_func(root_path)
  File "main.py", line 158, in infer
    return _infer(model, root_path)
  File "main.py", line 69, in _infer
    phase='test')
  File "/app/data_local_loader.py", line 51, in data_loader
    random_crop=is_train))
  File "/opt/conda/lib/python3.5/site-packages/torchvision/datasets/folder.py", line 209, in __init__
    target_transform=target_transform)
  File "/opt/conda/lib/python3.5/site-packages/torchvision/datasets/folder.py", line 87, in __init__
    "Supported extensions are: " + ",".join(extensions)))
RuntimeError: Found 0 files in subfolders of: /data/8_iret_food/test/test_data
Supported extensions are: .jpg,.jpeg,.png,.ppm,.bmp,.pgm,.tif,.tiff,webp

**Comment by nsml-admin** [comment]
안녕하세요,

해당에러는 유저의 코드부분에서 발생한것이라서 저희가 도와드리기에는 한계가 있어보입니다.

참고로 데이터셋의 위치는 `/data/8_iret_food/test/test_data` 상에 위치해있고, 파일들 또한 `이름.jpg`형식으로 되어있습니다.

```bash
/data/8_iret_food/test/test_data
    ~~~1.jpg
    ~~~2,jpg
    ~~~3,jpg
    ....
```
