### ISSUE TITLE
Question/submit관련(1_reg_dust)

### ISSUE THREAD

**Issue by garosu** [ai-starthon/AI_Starthon2019#193]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your NSML login ID?**

**Question**
1_reg_dust 문제를 수행하고 있습니다.
학습은 잘 되고 있는데, submit을 하면 아래와 같은 에러가 발생합니다.
=========================================================
Failed to evaluation
Traceback (most recent call last):
  File "/data/1_reg_dust/evaluation.py", line 70, in <module>
    print(evaluate(config.prediction, label_path))
  File "/data/1_reg_dust/evaluation.py", line 51, in evaluate
    mse_score = ic_metric(gts, ppreds)
  File "/data/1_reg_dust/evaluation.py", line 28, in ic_metric
    mse_score = weighted_mse(targets, predicts)
  File "/data/1_reg_dust/evaluation.py", line 11, in weighted_mse
    w_mse = 0.3*mean_squared_error(gt[:,0], pred[:,0]) + 0.7*mean_squared_error(gt[:,1], pred[:,1])
  File "/usr/local/lib/python3.5/site-packages/sklearn/metrics/regression.py", line 241, in mean_squared_error
    y_true, y_pred, multioutput)
  File "/usr/local/lib/python3.5/site-packages/sklearn/metrics/regression.py", line 77, in _check_reg_targets
    check_consistent_length(y_true, y_pred)
  File "/usr/local/lib/python3.5/site-packages/sklearn/utils/validation.py", line 205, in check_consistent_length
    " samples: %r" % [int(l) for l in lengths])
ValueError: Found input variables with inconsistent numbers of samples: [5448, 2]
==========================================================

**Comment by jungwoo-ha** [comment]
prediction을 위한 inference 코드에 버그가 있는 것으로 보입니다. 현재 2개만 predicted 되는 것으로 보이는 데 코드 버그를 확인하시면 좋을 것 같습니다. (5448은 gt 샘플 숫자 입니다.)
